# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='borrowedbook',
            unique_together=set([('user_login', 'book_id')]),
        ),
    ]
