# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_server', '0002_auto_20161205_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_server.Book'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='user_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
