# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 14:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_server', '0003_auto_20161205_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='user_login',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='borrowedbook',
            unique_together=set([('user', 'book')]),
        ),
    ]
