# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_server', '0004_auto_20161205_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.CharField(default='http://placehold.it/700x400', max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='requestFreq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
