# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_server', '0005_auto_20161205_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.datetime.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_server.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='pub_date',
            new_name='borrow_date',
        ),
        migrations.AlterUniqueTogether(
            name='bookrequest',
            unique_together=set([('user', 'book')]),
        ),
    ]
