# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_server', '0006_auto_20161217_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='requestFreq',
        ),
    ]
